### ISSUE TITLE
airplane, no network location

### ISSUE THREAD

**Issue by phalTowers** [gabm/FancyPlaces#12]
When network location fails why is there no GPS fallback?

**Comment by gabm** [comment]
Have you tried the latest beta version [here](https://www-user.tu-chemnitz.de/~gabm/FancyPlaces/FancyPlaces.apk)? currently there has been a lot of changes since the last release...

Actually it should retrieve your location using gps and network as well. But if there is a problem, please give me detailed steps to reproduce and information about your android screen...

**Comment by phalTowers** [comment]
Ah. 1.1.0 asked for Request Location Updates. GPS pin blinked. The update became available some moments after I posted. 

Should I install your beta/debug 1.1.0 version?

**Comment by phalTowers** [comment]
(I had been using 1.0.3. I apologize for not including that in my OP)

**Comment by gabm** [comment]
please try the version that is included in my first post and report back if everything works as you would expect it..
